export const datas ={
    country:'NIGERIA',
    data:[
        {
            id:'1',
            day:'monday',
            img:'https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png',
            temp:29
        },
        {
            id:'2',
            day:'tuesday',
            img:'https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png',
            temp:29
        },
        {
            id:'3',
            day:'wednessday',
            img:'https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png',
            temp:29
        },
        {
            id:'4',
            day:'thursday',
            img:'https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png',
            temp:29
        },
        {
            id:'5',
            day:'friday',
            img:'https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png',
            temp:29
        },
        {
            id:'6',
            day:'saturday',
            img:'https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png',
            temp:29
        },
        {
            id:'7',
            day:'sunday',
            img:'https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png',
            temp:29
        },
    ]
}